COQDOCEXTRAFLAGS := -g --parse-comments
COQEXTRAFLAGS := -w -implicit-core-hint-db,-deprecated-instance-without-locality

pre-all::
	+make -C coqrel
	+make -C compcert depend
	+make -C compcert

clean::
	+make -C coqrel clean
	+make -C compcert clean

-include Makefile.user
